services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_interview_simulator
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  # !!! instead of gemini if needed
  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   healthcheck:
  #     test: ["CMD-SHELL", "ollama list || exit 1"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10

  # ollama-init:
  #   image: ollama/ollama:latest
  #   depends_on:
  #     ollama:
  #       condition: service_healthy
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   entrypoint: ["ollama", "pull", "llama3.2:3b"]
  #   environment:
  #     OLLAMA_HOST: http://ollama:11434

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/ai_interview_simulator
      REDIS_URL: redis://redis_container:6379/0
    depends_on:
      db:
        condition: service_healthy
      # if u use ollama instead of gemini
      # ollama-init: 
      #   condition: service_completed_successfully
      redis_container:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - app
    
  redis_gui:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis_container

  redis_container:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  pgdata: {}
  ollama_data: {}
  redis_data: {}
